/**
 * Base diegética comprimida (fandom Vampire; sin texto oficial White Wolf).
 */

export type LoreFamily =
  | "si_shadow"
  | "masquerade_cost"
  | "blood_economy"
  | "city_institutions"
  | "court_whisper"
  | "marginal_humanity"
  | "chile_urbana"
  | "beast_pulse";

export const LORE_BY_FAMILY: Record<LoreFamily, readonly string[]> = {
  si_shadow: [
    "La ciudad compara comportamientos con rutas nocturnas: si la cifra se ensucia, aparece gente de chaleco antes de folklore nuevo en el bloc de notas.",
    "Un dron barato deja huella práctica porque sella hora, punto y carpeta de convenio municipal ambiguo con sello corporativo aburrido.",
    "La cruz nueva puede ser analista con presupuesto que clasifica alto riesgo repetido tres noches seguidas hasta que el hábito huele a firma.",
    "Los servidores archivan sombras mejor que tus libretas humanas y adoran series repetidas que se ven feas en cualquier dashboard.",
    "Cuando el helicóptero del noticiero ronda a veces no buscan titular: miden cuánto aguanta el cordón antes de seguridad ciudadana con voz de hierro.",
    "Las antenas no juzgan; acumulan costumbre de trayecto hasta que un tablero decide que repetir es sospechoso.",
    "La denuncia anónima es clip comprimido que suena fatal ante fiscal distraído y creíble en foro barrial con moderador cansado.",
    "Hay anexos contractuales que huelen a mapas térmicos y apenas muestran la cara de quien ordenó la comparación.",
    "Concertina recién puesta en pasaje viejo huele a permiso timbrado y a prisa contra el peatón libre después de medianoche.",
    "Un allanamiento con cámara encendida puede ser espectáculo digital antes de que el papel claro llegue con sello citable.",
    "Si el rumor urbano etiqueta tu edificio, la segunda visita puede parecer mantención barata repetida hasta el aburrimiento.",
    "Hay equipos de inquisición portátil que muerden con filas administrativas como muerden con estadísticas medio resueltas.",
    "Vender desconfianza catalogada es negocio rentable y tu sombra puede quedar con código neutro y frío.",
    "Patrón de movimiento y rumor camarilla pueden acabar en el mismo servidor si archivan etiquetas mal leídas igual.",
    "La sirena compite con la app vecinal y ninguna aclara cómo quedaste marcado en el turno anterior.",
  ],
  masquerade_cost: [
    "La Máscara es hábito muscular hasta que tus mejillas aprendan el cansancio humano como el peatón que llegó tarde y rechaza drama nuevo.",
    "Si quien lava vasos huele transpiración sin suficiente olor mortal, el velo se rompe antes de una excusa bien armada desde salón alto.",
    "La ignorancia colectiva pactada es un truco simple: todos miran medio milímetro menos fuerte a cambio de dormir tranquilos esa noche.",
    "Ascensor limpio bajo neón cruel puede cobrarte más trabajo que una página de etiqueta escrita por harpía divertida igual cansada.",
    "Taxista medio cuenta folklore laboral mal pagado con la misma cadencia con la que mediría un distrito largo y honesto.",
    "El celular grabando es estaca digital: el rumor sube intacto antes de que sangre manche la vereda demasiado pronto.",
    "A veces aprender seguridad ciudadana realista preserva mejor el velo que Auspex porque la cámara no ve intención, ve ángulos.",
    "El olvido colectivo es fatiga: misma tragedia contada dos veces mal y la ciudad convenga en ignorar para seguir viva.",
    "Modulas la voz demasiado bien en bar mediocre y delatas como con perfume equivocado en distrito equivocado.",
    "La etiqueta no es tratado legal: es saber entrar después del humo y no ser quien rompe el orden porque ese paga el rumor primero.",
    "Máscara rota cuesta desplazar la misma piedra por otra entrada: regla táctica nueva, permiso frágil, sombra vieja que huele a ti.",
    "La ignorancia negociada se rompe con uniforme y pregunta directa o con segundo mortal y cámara encendida antes de pacto claro.",
    "Reflejo en vidrio pacta con neón: pupila demasiado serena delata tiempo detenido bajo farola helada.",
    "Rumor muy limpio y muy rápido rara vez es accidente: alguien empujó la escena como empujó la ventana equivocada a medianoche.",
    "Espejo de taxi sucio no perdona: pupila serena, pestañeo lento, niebla de escape barato en vereda fría.",
  ],
  blood_economy: [
    "La sangre circula como moneda tácita: acumularla sin retorno enferma el barrio más rápido que decreto.",
    "Deuda de favores es barata hasta que el acreedor cobra con interés compuesto de miedo.",
    "Un neonato hambriento sube el precio del silencio en tres cuadras sin que nadie hable en el salón.",
    "El traficante mortal no sabe qué vende; sabe que el cliente paga extra por horario y puerta trasera.",
    "Sangre de calle barata envenena el paladar y obliga a repetir dosis: economía de escasez fabricada.",
    "Quien dona plasma en vano no firma pacto pero deja rastro caliente para quien cata números desde sombra.",
    "La reserva en frío es capital guardado por ancianos para sequía o guerra de desgaste.",
    "Secreto compartido entre dos es vitae a medias: alguien queda con porción pequeña casi siempre.",
    "Rebaño consentido aguanta hasta primer rumor grave de desaparecidos y después todo sube tarifa y paranoia igual.",
    "Limpieza tras atracón mediocre cobra igual ghoul igual camarero: nadie gratis si hay cámara en la esquina.",
    "Hospital incógnito y vereda luminosa suben tarifa en temporada fea cuando humanos escasean sin contrato escrito sobre mesa igual.",
    "Anciano que cuenta gotas en vaso de agua mide escasez con reloj silencioso y sonrisa de archivo igual.",
    "Ghoul endeudado cobra en un abrazo educado usando pupila dulce igual mano helada igual rumor fino igual.",
    "Campaña de donación igual escenario de carisma y hambre con logo municipal medio honesto medio peligrosísimo.",
    "Sangre vieja guardada huele a cera y papel igual cuando abris frasco huele igual guerra igual antigua repetida.",
  ],
  city_institutions: [
    "Municipalidad y fiscalía compiten por la misma carpeta; quien clava primero el clip impone versión oficial con olor a detergente.",
    "Bomberos entran antes que abogados: el humo firma mejor una escena provisional que cualquier declaración escrita con calma.",
    "La sala de urgencias es filtro humano barato para el Estado y carísima si no sabes ocultar hambre o confianza mortal.",
    "Comisaría de noche huele a café rancio y plástico; confesiones y silencios suenan igual contra el vidrio recién instalado.",
    "Registro Civil guarda nombres que ya no te sirven; cada trámite escribe línea en servidor que otros leen sin pedir permiso.",
    "Inspección con casco puede ser vecino apurado o técnico serio con lápiz y foto en puerta medio sellada o medio abierta.",
    "Permiso de obra abre zanja y vista hacia sótano mal sellado; el hedor sube como rumor barrial pesado igual honesto igual.",
    "El transporte madrugador es refugio barato hasta que cámara nueva convierte vagón entero en vitrina helada medio honesta medio.",
    "Biblioteca municipal huele humedad y papel; secretos duermen en índices que nadie revisa por costumbre respetuosa al aburrimiento.",
    "Funeral modesto es teatro humano de fila fría: escenario silencioso para camarilla que escucha sin brillar más de lo necesario.",
    "Plaza escolar vacía tras censo vuelve acústica al rumor incluso detrás de cortina gruesa que finge estar de adorno igual.",
    "Alcaldesa bajo foco calienta piel mortal nueva y enfría sombras políticas en porticos cortos fríos y silenciosos.",
    "Oficinas con olor institucional a cinta y papel fresco archivan sombras legales ambiguas antes de cualquier firma clara nueva.",
    "Hidrante tapado y obra improvisada devuelven a la escalera curiosa tres miradas de más por turno medio honestas y medio peligrosas.",
    "Subestación con zumbido constante enmascara conversaciones bajas que nadie autorizó del todo cuando el horario es frío igual humano igual.",
  ],
  court_whisper: [
    "Salón vacío con copas llenas aguarda duelo de susurros antes del micrófono oxidado.",
    "Las harpías practican rumor como tensan el arco: sin público, suena igual de filoso y carísimo de reputación.",
    "Detrás de cortina gruesa, el anfitrión finge sordera cortés mientras cataloga cada palabra perdida.",
    "Silla improvisada puede mandar como trono caro si quien ocupa narra historias suficientemente costosas.",
    "Entre humo espeso, un voto a medias suena a juicio político improvisado y peligrosísimo.",
    "Pacto sellado con saliva cortés y vino mediocre suena a teatro barato hasta que la deuda pesa en sangre real.",
    "El espía mortal del catering oye mejor que el neonato brillante en primera fila apurado por brillar.",
    "Acuerdos en pasillo angosto huelen a metal y ego; el eco queda guardado hasta el amanecer administrativo.",
    "Anillo ancestral en dedo fresco pesa más que etiqueta fina con curva educada y sonrisa incómoda.",
    "Sobremesa con cigarros apagados funciona como confesionario donde un susurro alcanza para condenar la noche.",
    "Mirada fija en copa vacía delata hambre política con frío administrativo encima de la sonrisa cortés.",
    "Anciano dormido en sillón no promete inutilidad: oídos viejos captan rumor fino que jóvenes pasan por alto.",
    "La salida de servicio deviene emboscada culta: guantes blancos, sonrisa incómoda, rumor fino en el aire.",
    "El elogio susurrado es cuchillo de salón que corta sin manchar alfombra y deja rumor limpio sobre la mesa.",
    "Un rumor demasiado limpio se fractura si el mismo clip filtra tres veces en una sola noche fría.",
  ],
  marginal_humanity: [
    "Peatón cansado deja de mirar dos veces la misma sombra porque la calle cobra supervivencia antes que curiosidad.",
    "Carpa bajo puente guarda calor humano barato y olor a plástico quemado que incomoda hasta a la Bestia.",
    "El perro callejero huele hambre antes de que el humano sea consciente y ladra en el peor instante posible.",
    "El recolector nocturno con carrito chirriante suena más honesto que el informe municipal recién impreso.",
    "El repartidor en moto trae comida caliente y prisa mortal que no respeta jerarquías antiguas de salón.",
    "El niño en la vereda aprende a leer sombra antes que cartel municipal con letra pequeña y aburrida.",
    "El artista de esquina vende humo colorido y silencio barato que tapa conversaciones incómodas detrás.",
    "El veterano en banco público recuerda explosiones que no encajan el tono elegante de un distrito caro.",
    "La enfermera sale del turno con ojeras que el café barato no disimula del todo ni con fe.",
    "El portero con control remoto conoce tus horarios de ausencia mejor que la libreta de un escriba en salón.",
    "Los chismes entre vecinas barren la calle con precisión quirúrgica porque así se alimenta el barrio igual.",
    "La empleada de limpieza ve manchas que la narrativa institucional decide ignorar con devoción religiosa igual.",
    "El microvendedor esquiva fiscalización con la misma astucia desesperada con la que esquiva el hambre.",
    "La manta fina en invierno mide indiferencia barrial con crueldad clara y matemática igual honesta.",
    "El abuelo en la plaza alimenta palomas demasiado quieto para ser sólo abuelo igual simple.",
  ],
  chile_urbana: [
    "La cordillera empuja el aire seco y la niebla costera cuelga en el valle como un velo nuevo húmedo.",
    "Un sismo lejano recuerda que la ciudad descansa sobre memoria geológica que no vota ni pide permiso en salón.",
    "El microclima entre torres engaña el abrigo y obliga una capa extra en la esquina donde sube viento helado.",
    "Barrio en ladera con rejas publicitarias de seguridad mientras el rumor sube la tarifa barata del miedo.",
    "El taco nocturno en autopista es confesionario moderno entre plásticos limpios y mugre encajada igual.",
    "Fiesta clandestina con cumbia mezcla sudor mortal y hambre nocturna sin carnet oficial claro todavía igual.",
    "Parrilla con carbón en la vereda regala humo honesto y carne confiable en un turno que la Bestia respeta medio.",
    "La feria con fruta barata abre conversaciones francas que la Bestia observa con interés medio hambriento igual.",
    "Bus vacío a medianoche gela el asiento plástico y el eco del motor cansado enmascara susurros recién nacidos.",
    "La brisa salada en costanera enmascara el olor dulce de sangre reciente sobre muelle abandonado y oscuro.",
    "Sendero oscuro en cerro es atajo mortal y trampeo de sombras que no garantiza ninguna cortesía formal.",
    "Vendedor informal en metro ofrece cable barato y excusa curiosa igual tres miradas de más igual por turno.",
    "Titular chillón del noticiero nocturno empuja miedo barato que compite con el rumor más limpio del barrio.",
    "Uniforme escolar arrugado huele a calor adolescente igual mezcla confundible con hambre mortal recién abierta igual.",
    "Fiesta patriótica con bandera y soda empaqueta multitud mortal que ignora listas escritas desde poder serio igual.",
  ],
  beast_pulse: [
    "La Bestia respira bajo lengua antes de que cierres la primera frase mortal y reclama turno claro igual.",
    "El pulso acelera ante el olor fresco de herida ajena que todavía te llama con nombre medio humano medio.",
    "Los dientes aprietan cuando alguien toca tu hombro sin permiso claro frente calle nueva oscura nueva.",
    "Manos frías engañan a boca caliente si corazón late fuerte por prisa nerviosa barata y repetida nueva.",
    "La Bestia adora espejos sucios porque distorsionan la vergüenza en una figura abstracta barata y cómoda.",
    "Tu silencio interior gruñe cuando música dulce tapa las conversaciones que importan más que melodía nueva.",
    "La Bestia aborrece ascensor espejado que baja desde piso veinte a lobby demasiado iluminado igual humano.",
    "Te sube la saliva cuando alguien miente con voz humana perfecta frente tuyo tres veces seguidas sin rubor.",
    "Negociación larga e incienso frito abruman el aire hasta que la Bestia roza uñas contra palmas igual quietas.",
    "Gaita distante confunde a la Bestia mezclando folklore humano con pulso de acecho que no entiende del todo.",
    "Escalera angosta con olor a detergente barato aprieta la paciencia igual aprieta bestia esperando turno claro.",
    "Neón parpadeante iguala ritmo de cazador que mide distancia antes del primer mordisco educado igual fino.",
    "Azúcar barata en paladar dispara salivación no pedida y delata hambre escondida con crudeza animal igual.",
    "Silbato de árbitro lejano golpea un nervio primitivo igual silbato de seguridad en centro comercial cerrado.",
    "Luz de faro móvil en rostro ajeno despierta pulso de acecho que fingías dormido hace rato igual honesto.",
  ],
};